version: '3.10'

services:
  server:
    build: .
    ports:
      - "8001:8000"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=denchik2702
      - POSTGRES_DB=telebon
    volumes:
      - ./structure.sql:/docker-entrypoint-initdb.d/structure.sql
      - ./data:/var/lib/postgresql/data
  #server:

networks:
  default: